version: '3.8'

networks:
  wodo_gamehub:
    name: 'wodo_gamehub'

services:
  gamehub:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: gamehub
    depends_on:
      - mysql
      - redis
    ports:
      - "8091:80"
    networks:
      - wodo_gamehub

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "4306:3306"
    volumes:
      - ./mysqldata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wodo_gamehub
      MYSQL_USER: wodo
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - wodo_gamehub

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redisdata:/data
    networks:
      - wodo_gamehub

  soketi:
    image: 'quay.io/soketi/soketi:latest-16-distroless'
    container_name: soketi
    environment:
      DEBUG: '1'
      METRICS_SERVER_PORT: '9601'
    ports:
      - '${SOKETI_METRICS_SERVER_PORT:-9601}:9601'
    networks:
      - wodo_gamehub

  soketi_nginx:
    build:
      context: ./docker-dev
      dockerfile: soketi-nginx.dockerfile
    container_name: soketi-nginx
    depends_on:
      - soketi
    ports:
      - "2053:6002"
    networks:
      - wodo_gamehub
    volumes:
      - ./../keys:/keys
