#!/usr/bin/env bash

# Run PHP-FPM as current user
if [ ! -z "$WWWUID" ]; then
  sed -i "s/user\ \=.*/user\ \= $WWWUID/g" /etc/php/8.1/fpm/pool.d/www.conf

  # Set UID of user "ubuntu"
  usermod -u $WWWUID ubuntu
fi


# Ensure /.composer exists and is writable
if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

if [ $# -gt 0 ]; then
    # if we passed a command, then run it
    exec gosu $WWWUID "$@"
else
  # Else default to supervisord
  /usr/bin/supervisord
fi

